const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHATS";

const NEW_MESSAGE = "NEW_MESSAGE";
const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE";

const NEW_REQUEST = "NEW_REQUEST";

const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";

const CHAT_JOINED = "CHAT_JOINED";
const CHAT_EXITED = "CHAT_EXITED";

const ONLINE_USERS = "ONLINE_USERS";

export {
  ALERT,
  CHAT_EXITED,
  CHAT_JOINED,
  NEW_ATTACHMENT,
  NEW_MESSAGE,
  NEW_MESSAGE_ALERT,
  NEW_REQUEST,
  ONLINE_USERS,
  REFETCH_CHATS,
  START_TYPING,
  STOP_TYPING
};

